from typing import Protocol, AsyncIterator, Self
from protocol.types import SignalChunk

class ProtocolStreamReaderProtocol(AsyncIterator[SignalChunk]):
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> SignalChunk: ...
    async def close(self) -> None: ...
    async def acknowledge_packet(self) -> None: ...
    async def authenticate(self, token: str) -> None: ...
